### ISSUE TITLE
CUDA doesn't work in containers until after use in host OS (problem with device files dynamically created in host OS)

### ISSUE THREAD

**Issue by daikema** [apptainer/singularity#1441]
## Version of Singularity:

Initially noticed in 2.4.5, testing using 2.5.0-rc1 now

### Expected behavior

CUDA works in containers right away.

### Actual behavior

CUDA doesn't work in containers until after I've run a process on the host OS which does something with a GPU.

Poking around it looks as though with the latest drivers installed on CentOS 7.4, device files are created dynamically when running programs which require them (and for at least one case an additional kernel module is loaded in addition to the other nvidia ones already loaded), but this process does not work when running in a container.  In the "Steps to Reproduce Behavior" section I show results with `nvidia-smi` and `bandwidthTest` from the CUDA's `extras/demo_suite`.

Before running `nvidia-smi` on the host machine, `ls /dev | grep -i nvidia` returns nothing (but a number of nvidia drivers are loaded looking at the `lsmod` output).  After running `nvidia-smi` on the host, `ls /dev | grep -i nvidia` returns:
```
crw-rw-rw-.  1 root root    195, 255 Apr  5 15:04 nvidiactl
crw-rw-rw-.  1 root root    195,   0 Apr  5 15:04 nvidia0
crw-rw-rw-.  1 root root    195,   1 Apr  5 15:04 nvidia1
```

And then when I run `/usr/local/cuda/extras/demo_suite/bandwidthTest` on the host machine the following also appears (and `lsmod` shows the `nvidia_uvm` kernel module has been dynamically loaded):
```
crw-rw-rw-.  1 root root    195, 255 Apr  5 15:04 nvidiactl
crw-rw-rw-.  1 root root    195,   0 Apr  5 15:04 nvidia0
crw-rw-rw-.  1 root root    195,   1 Apr  5 15:04 nvidia1
crw-rw-rw-.  1 root root    237,   1 Apr  5 15:05 nvidia-uvm-tools
crw-rw-rw-.  1 root root    237,   0 Apr  5 15:05 nvidia-uvm
```

So, *depending on which command is executed different device files appear to be dynamically created (and I suspect that this may not be a complete list).*

Device files are available in the containers as soon as they're created in the host OS.  If I leave a terminal with a container running where I just ran `nvidia-smi` and had it produce an error, then if I open up a second terminal window and execute `nvidia-smi` on the host, I can then go back to the still-running container and now run `ndivia-smi` in my first terminal without it producing an error.  No need to restart that container.

### Steps to reproduce behavior

(reboot system to reinitialize OS, GPUs, etc.)

In this case, the host machine is running CentOS 7.4, and I've tested with containers using both Ubuntu 16 and CentOS 7.  I'm using the CUDA version currently available from NVIDIA's repos for CentOS 7.4 (930.30).

(The issues here were initially found using testing some custom software.  In the results here I've added `/usr/local/cuda` to the bind path to give some common demo apps to illustrate the problem with).

Launch container (in my case `singularity shell --nv dave-gpu-2.5/`).

Execute some commands:

```
Singularity dave-gpu-2.5:~/dave-gpu> nvidia-smi 
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
Singularity dave-gpu-2.5:~> /usr/local/cuda/extras/demo_suite/bandwidthTest 
[CUDA Bandwidth Test] - Starting...
Running on...

cudaGetDeviceProperties returned 30
-> unknown error
CUDA error at /dvs/p4/build/sw/rel/gpgpu/toolkit/r9.1/demo_suite/bandwidthTest/bandwidthTest.cu:255 code=30(cudaErrorUnknown) "cudaSetDevice(currentDevice)" 
Singularity dave-gpu-2.5:~/dave-gpu>  /usr/local/cuda/extras/demo_suite/bandwidthTest --device=all
[CUDA Bandwidth Test] - Starting...
cudaGetDeviceCount returned 30
-> unknown error
```

Exit container.

Run `/usr/local/cuda/extras/demo_suite/bandwidthTest` on the host OS (which works properly).

Relaunch container (using the exact same parameters as before).  Rerun the exact same commands as before.

```
Singularity dave-gpu-2.5:~/dave-gpu> nvidia-smi 
Thu Apr  5 11:53:17 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:06:00.0 Off |                    0 |
| N/A   28C    P0    28W / 250W |      0MiB / 12198MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  Off  | 00000000:83:00.0 Off |                    0 |
| N/A   28C    P0    27W / 250W |      0MiB / 12198MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Singularity dave-gpu-2.5:~> /usr/local/cuda/extras/demo_suite/bandwidthTest 
[CUDA Bandwidth Test] - Starting...
Running on...

 Device 0: Tesla P100-PCIE-12GB
 Quick Mode

 Host to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)    Bandwidth(MB/s)
   33554432            11608.7

 Device to Host Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)    Bandwidth(MB/s)
   33554432            12838.3

 Device to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)    Bandwidth(MB/s)
   33554432            380273.3

Result = PASS

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.
Singularity dave-gpu-2.5:~/dave-gpu>  /usr/local/cuda/extras/demo_suite/bandwidthTest --device=all
[CUDA Bandwidth Test] - Starting...

!!!!!Cumulative Bandwidth to be computed from all the devices !!!!!!

Running on...

 Device 0: Tesla P100-PCIE-12GB
 Device 1: Tesla P100-PCIE-12GB
 Quick Mode

 Host to Device Bandwidth, 2 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)	Bandwidth(MB/s)
   33554432			23151.8

 Device to Host Bandwidth, 2 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)	Bandwidth(MB/s)
   33554432			25655.7

 Device to Device Bandwidth, 2 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)	Bandwidth(MB/s)
   33554432			756934.6

Result = PASS

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.
```

(If I run `nvidia-smi` in the host OS after the initial failure, `nvidia-smi` works in the container afterwards but `/usr/local/cuda/extras/demo_suite/bandwidthTest` doesn't ... at least not until I've run it on the host OS).

**Comment by GodloveD** [comment]
Hi @daikema this came up yesterday in the Singularity Slack discussion as well.  

Basically the problem (as I understand it) is `nvidia-modprobe`.  I think that `nvidia-modprobe` probes the kernel to see of the `nvidia_uvm` module is loaded.  If not, it loads the module on the users behalf. This is usually called by CUDA and everything works fine.  

But `nvidia-modprobe` runs with an suid bit.  So it won't work inside the container where `no_new_privs` is set.   And this is by design.  Singularity disallows suid programs from running inside of the container as a basic design principle.  

I don't really have a good solution to this issue.  I'd be happy to hear suggestions if anybody else has ideas.

**Comment by daikema** [comment]
> I don't really have a good solution to this issue. I'd be happy to hear suggestions if anybody else has ideas.

Reading more I found [your earlier comment about `nvidia-container-cli`](https://github.com/singularityware/singularity/issues/1253#issuecomment-357836912) which I wasn't previously using.  With that installed I can now run `nvidia-smi` without problems inside the container straight after boot.  However, `/usr/local/cuda/extras/demo_suite/bandwidthTest` still failed (I think due to the lack of `nvidia-uvm`).

I think that this seems like it could now be solved with a fix to `nvidia-container-cli` though rather than `singularity`.  e.g. I ran `nvidia-container-cli --debug=/tmp/libnvidia-container.txt list` right after booting as I'd sort heard suggested at some website or other to check something or other (and had it working properly prior to the reboot).  It dies with the following error:
```
nvidia-container-cli: initialization error: cuda error: unknown error
```
And in my debug logs I see the following:
```
-- WARNING, the following logs are for debugging purposes only --

I0406 14:11:16.289664 4059 nvc.c:274] initializing library context (version=1.0.0, build=be797da00b156493e80f1ae6f38d69f23c932554)
I0406 14:11:16.290119 4059 nvc.c:248] using root /
I0406 14:11:16.290130 4059 nvc.c:249] using ldcache /etc/ld.so.cache
I0406 14:11:16.290140 4059 nvc.c:250] using unprivileged user 1000:1000
I0406 14:11:16.293856 4060 driver.c:136] starting driver service
I0406 14:11:16.337751 4059 driver.c:224] driver service terminated with signal 15
```

The same error results if I first launch a container, run `nvidia-smi` inside (without errors), exit and then run the `nvidia-container-cli --debug=/tmp/libnvidia-container.txt list` command on the host OS.

Run bandwidth test on host operating system, and then run `nvidia-container-cli --debug=/tmp/libnvidia-container.txt list` again.  This time it spits out:
```
/dev/nvidiactl
/dev/nvidia-uvm
/dev/nvidia-uvm-tools
/dev/nvidia-modeset
/dev/nvidia0
/dev/nvidia1
/usr/bin/nvidia-smi
/usr/bin/nvidia-debugdump
/usr/bin/nvidia-persistenced
/usr/bin/nvidia-cuda-mps-control
/usr/bin/nvidia-cuda-mps-server
/usr/lib64/nvidia/libnvidia-ml.so.390.30
/usr/lib64/nvidia/libnvidia-cfg.so.390.30
/usr/lib64/nvidia/libcuda.so.390.30
/usr/lib64/nvidia/libnvidia-opencl.so.390.30
/usr/lib64/nvidia/libnvidia-ptxjitcompiler.so.390.30
/usr/lib64/nvidia/libnvidia-fatbinaryloader.so.390.30
/usr/lib64/nvidia/libnvidia-compiler.so.390.30
/usr/lib64/nvidia/libnvidia-encode.so.390.30
/usr/lib64/nvidia/libnvcuvid.so.390.30
/usr/lib64/nvidia/libnvidia-eglcore.so.390.30
/usr/lib64/nvidia/libnvidia-glcore.so.390.30
/usr/lib64/nvidia/tls/libnvidia-tls.so.390.30
/usr/lib64/nvidia/libnvidia-glsi.so.390.30
/usr/lib64/nvidia/libnvidia-fbc.so.390.30
/usr/lib64/nvidia/libnvidia-ifr.so.390.30
/usr/lib64/nvidia/libGLX_nvidia.so.390.30
/usr/lib64/nvidia/libEGL_nvidia.so.390.30
/usr/lib64/nvidia/libGLESv2_nvidia.so.390.30
/usr/lib64/nvidia/libGLESv1_CM_nvidia.so.390.30
```

**So installing `nvidia-container-cli` was a partial fix, and `nvidia-container-cli` seems to have problems executing certain functions until I've run an app that'll cause the `nvidia_uvm` driver to be loaded - basically the same sort of problem that I was having in `singularity` yesterday.**  So basically I suspect that if this upstream issue is resolved then installs using `--nv` with the `nvidia-container-cli` software installed should work without problems.

On a semi-related note, are there any plans to bind in a more comprehensive set of NVidia libraries?  When instead of running the demo suite app I tried to build the software I actually want to use it required that I modify `nvliblist.conf` to bind in a few more libraries (`libcudart.so`, `libcufft.so`, `libcufftw.so` in my case ... although there are quite a few more in `/usr/local/cuda/lib64` on my machine that I could imagine various apps wanting to use.  I'm guessing it's probably going to cause problems if I use version 7.5 of the fft library in my container, linked against version 9.1 of the main library).

**Comment by daikema** [comment]
Interesting - so someone else (i.e. you @GodloveD) reported seeing similar output in [this libnvidia-container issue](https://github.com/NVIDIA/libnvidia-container/issues/3).  In that case it seemed that the solution to fully load the driver was to `sudo nvidia-container-cli -k -d /dev/tty list -cuv`

Not quite sure how `nvidia-container-cli` is called by singularity, but could similar parameters be passed in then as well to achieve the fix we're looking for here?

EDIT: `sudo nvidia-container-cli -k list` seems to be the current version of this command (and unfortunately requires sudo even though you'd mentioned `nvidia-mobprobe` runs with suid bit set).  I wonder if the best approach (awaiting a more permanent fix) is just to do this in an init script on the machines I've got with GPUs.

**Comment by GodloveD** [comment]
I'd have to look at it a bit more deeply.  Not sure we would want to call `nvidia-container-cli` with full privs from within singularity or not because then we would be extending the attack surface of singularity out to code we don't control.

**Comment by dtrudg** [comment]
One option for a workaround, if you are running on clusters, is to call a very small, quick CUDA executable without side-effects (e.g. just doing a devicequery) from a scheduler prolog script for GPU jobs.

**Comment by daikema** [comment]
I'm not sure that we want to call `nvidia-container-cli` with full privileges either.

I'm just kind of confused why `nvidia-container-cli` is built to require you to run it `sudo` to fully load the kernel modules / create the device files **but** you can load kernel modules without requiring `sudo` by running a small CUDA executable before singularity GPU tasks as @dctrud suggested.

i.e. is there some reason why this shouldn't be considered an upstream issue with `nvidia-container-cli`?

**Comment by flx42** [comment]
> I'm just kind of confused why nvidia-container-cli is built to require you to run it sudo to fully load the kernel modules / create the device files but you can load kernel modules without requiring sudo by running a small CUDA executable before singularity GPU tasks as @dctrud suggested.

No. Remove `nvidia-modprobe` and it won't work.

**Comment by dtrudg** [comment]
The suggestion of running a small CUDA executable on the host (via scheduler prolog script or similar, not in the container) is relying on `nvidia-modprobe` as that is what will be called when the uvm module is needed.

**Comment by michaelmoore10** [comment]
As a suggestion.  NVIDIA provides an init service, nvidia-persistenced, that installs the GPU drivers on boot up and sets them to remain resident in memory.  By default, the drivers and devices get unmapped after a timeout.  NVIDIA recommends using nvidia-persistenced instead of running device query.  In my testing with Singularity and CUDA containers, I do not have this issue (using 2.4.6).

**Comment by flx42** [comment]
@michaelmoore10 AFAIK, nvidia-persistenced doesn't load `nvidia_uvm`.
The only solution is to have proper `udev` rules, ask your administrator :)

**Comment by daikema** [comment]
I can confirm that it doesn't load `nvidia_uvm`.

**Comment by michaelmoore10** [comment]
@flx42 and @daikema - I am running CentOS 7.4 with the NVIDIA CUDA/Driver RPMs.  My puppet automation enables and starts the nvidia-persistenced service in systemd.  I am running the latest Singularity development-2.x code as of Wednesday, April 18, 2018, to enable access to the NVIDIA GPU Cloud repository.  Here is what I see when I start Singularity:

`[michael_moore@gna-r05r03u05b02 ~]$ singularity shell --nv  docker://nvcr.io/nvidia/cuda:9.0-cudnn7.1-devel-ubuntu16.04`
`<deleted downloading logs>`
`Singularity cuda:9.0-cudnn7.1-devel-ubuntu16.04:/dev> ls /dev | grep -i nvidia`
`nvidia-modeset`
`nvidia-uvm`
`nvidia-uvm-tools`
`nvidia0`
`nvidiactl`

`[root@gna-r05r03u05b02 x86_64]# systemctl | grep nvidia`
`  nvidia-persistenced.service                                                                      loaded active running   NVIDIA Persistence Daemon`

The nvidia-persistenced.service script comes from the xorg-x11-drv-nvidia package from NVIDIA's RHEL7 cuda repo.

I am not doing anything special to enable the devices.

**Comment by GuillaumeSmaha** [comment]
Try to load `nvidia-uvm` with `sudo modprobe nvidia-uvm`
If you have the error `modprobe: ERROR: could not insert 'nvidia_uvm': Required key not available` like me, you have an issue with SecureBoot which doesn't allow unsigned driver.

To solve this, see https://askubuntu.com/questions/762254/why-do-i-get-required-key-not-available-when-install-3rd-party-kernel-modules

**Comment by DrDaveD** [comment]
Can anyone confirm if this is still an issue with singularity-3?  If so, is there anything that singularity could do about it, or is this outside of its control?

**Comment by dtrudg** [comment]
This is still an issue - the `nvidia_uvm` module needs to be loaded. I'm still not sure that we want to have singularity call out to the setuid root helper on the host to do this, and we can't do it within the container.

**Comment by dtrudg** [comment]
This continues to be out of our hands, so I'm going to close the issue. I continue to believe, especially with progression toward rootless usage, that we don't want to call out to a setuid root binary on the host.
